version: 1.1.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: nuget restore
build:
  project: NetLib/NetLib.csproj
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: SugQAcpOZHYwtDpMPlkd+y8kxkwZ/IpE9u5GBq/9uHEu4vzd84QkqlwLEz2XPg8A
  on:
    branch: master  