version: 1.0.{build}
branches:
  only:
  - master
configuration: Release
platform: Any CPU
nuget:
  project_feed: true
build:
  publish_nuget: true
  verbosity: minimal
notifications:
- provider: Email
  to:
  - vildar82@gmail.com
  subject: appveyor netlib
  message: build
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true