version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
build:
  project: NetLib/NetLib.csproj
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: 3dkguU1xfhgsgGezjNpbdWGMiFrlqPCi/ZhTCt5MCmSJ6cS3sXtQqTU+t86tErvN
  on:
    branch: master